name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/cache@v2
      with:
        path: ~/.virtualenvs
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.*') }}
    - uses: pre-commit/action@v2.0.0
