name: testing

on:
  pull_request:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Pytest
      run: pip install --upgrade pytest
    - name: Test!
      run: pytest
